de.tudarmstadt.ukp.dkpro.core.matetools-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/matetools/MateLemmatizer.java, de.tudarmstadt.ukp.dkpro.core.matetools-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/matetools/MateMorphTagger.java, de.tudarmstadt.ukp.dkpro.core.matetools-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/matetools/MatePosTagger.java, de.tudarmstadt.ukp.dkpro.core.stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordDependencyConverter.java, de.tudarmstadt.ukp.dkpro.core.stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordLemmatizer.java, de.tudarmstadt.ukp.dkpro.core.stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordParser.java, de.tudarmstadt.ukp.dkpro.core.stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordPosTagger.java
Added missing type and feature capabilities to some tools
=> Added type capability annotations

de.tudarmstadt.ukp.dkpro.core.castransformation-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/castransformation/Backmapper.java
This is a first step in moving more towards using Uima Fit for these components
=> changed the Chain parameter to be more in line with UimaFit

README.md
I was frustrated by the redundant link to google code.
=> Project site now on github

de.tudarmstadt.ukp.dkpro.core.io.penntree-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/penntree/PennTreeToJCasConverter.java, de.tudarmstadt.ukp.dkpro.core.io.penntree-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/penntree/PennTreeToJCasConverterTest.java
=> Fixes #696

dkpro-core-castransformation-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/castransformation/ApplyChangesBackmapperTest.java
Added one test to verify that backmapping of general feature structures are mapped back and not only those of type Annotation. Removed no longer used imports.
=> Added test to backmapper for previous bug fix

pages/groovy-intro.md
Changed download location of gvm tool to https://get.sdkman.io"
=> Location of gvm tool has changed

dkpro-core-api-lexmorph-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/no-ud-pos.map, dkpro-core-api-syntax-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/syntax/tagset/no-universal-dependency.map, dkpro-core-io-lxf-asl/src/main/java/org/dkpro/core/io/lxf/internal/DKPro2Lxf.java, dkpro-core-udpipe-asl/pom.xml, dkpro-core-udpipe-asl/src/main/java/org/dkpro/core/udpipe/internal/UDPipe2DKPro.java, dkpro-core-udpipe-asl/src/scripts/build.xml, dkpro-core-udpipe-asl/src/test/java/org/dkpro/core/udpipe/UDPipeParserTest.java, dkpro-core-udpipe-asl/src/test/java/org/dkpro/core/udpipe/UDPosTaggerTest.java
This pull request contains a small fix to the LXF and Adding Norwegian support to UDPipe.
=> A Bug Fix to the LXF & Norwegian support to UDPipe

dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizerTrainer.java, dkpro-core-stanfordnlp-gpl/src/test/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizerTrainerTest.java, dkpro-core-stanfordnlp-gpl/src/test/resources/ner/README, dkpro-core-stanfordnlp-gpl/src/test/resources/ner/train-english.props
Here is my initial proposal for including a component for training a NER model with Stanford CoreNLP. See Issue #1000 .
=> Support training Stanford NER model

dkpro-core-treetagger-asl/pom.xml, dkpro-core-treetagger-asl/src/scripts/build.xml
I added an entry in the build.xml for a middle high german parameter file (gmh). And while I was at it, I also updated the checksums for (modern) English and German.
=> Tree tagger models

dkpro-core-doc/src/main/asciidoc/developer-guide.adoc, dkpro-core-doc/src/main/asciidoc/developer-guide/modules.adoc
First attempt at a chapter with information on what to observe when adding new modules to DKPro Core
=> #1145 - Documentation for creating new modules

dkpro-core-api-parameter-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/api/parameter/ComponentParameters.java, dkpro-core-lingpipe-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/lingpipe/LingPipeNamedEntityRecognizerTrainer.java, dkpro-core-opennlp-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpNamedEntityRecognizerTrainer.java, dkpro-core-opennlp-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/opennlp/internal/CasNameSampleStream.java, dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizerTrainer.java
This PR adds `@ConfigurationParameter` to NER trainers to build NER models for different variants.
=> Named Entity Filter for NER Trainers

dkpro-core-tokit-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/tokit/CamelCaseTokenSegmenter.java, dkpro-core-tokit-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/tokit/CamelCaseSegmenterTest.java
Jut let me know what I need to change.
=> #1180: Option to markup split tokens in CamelCaseTokenSegmenter

dkpro-core-io-ditop-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/ditop/DiTopWriter.java, dkpro-core-io-ditop-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/ditop/DiTopWriterTest.java, dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordSentimentAnalyzer.java, dkpro-core-stanfordnlp-gpl/src/test/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordSentimentAnalyzerTest.java
- Check usages of FileUtils.readLines
=> #1205 - Avoid using platform encoding

dkpro-core-io-brat-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/brat/internal/model/BratTextAnnotation.java
- Retain only the first element in the discontinous segment
=> #1210 - Handle discontinuous segments in brat format

dkpro-core-io-brat-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/brat/BratReader.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2000Writer.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2002Writer.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2003Writer.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2006Writer.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2008Writer.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2009Writer.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2012Writer.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/ConllUWriter.java, dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/WebannoTsv3XReader.java, dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/WebannoTsv3XWriter.java
- Fixed all missing metadata problems reported by the uimaFIT Maven plugin
=> #1259 - Improve component metadata (1.10.0)

dkpro-core-io-pdf-asl/NOTICE.txt, dkpro-core-io-pdf-asl/pom.xml, dkpro-core-io-pdf-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/pdf/PdfReader.java, dkpro-core-io-pdf-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/pdf/internal/Buckets.java, dkpro-core-io-pdf-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/pdf/internal/LegacyPDFStreamEngine.java, dkpro-core-io-pdf-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/pdf/internal/Pdf2CasConverter.java, dkpro-core-io-pdf-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/pdf/internal/PdfLayoutEventStripper.java, dkpro-core-io-pdf-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/pdf/internal/SubstitutionTrieParser.java, dkpro-core-io-pdf-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/pdf/internal/Trie.java
- Moved PDF parsing code to "internal" package
- Adjusted code to PDFBox 2.0.9
=> #1261 - Upgrade PdfReader to a more recent PdfBox version

dkpro-core-treetagger-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/treetagger/TreeTaggerChunker.java
=> #1267 - TreeTaggerChunker requires PARAM_MODEL_ENCODING

dkpro-core-api-datasets-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/datasets/lib/gum-en-conll-2.2.0.yaml, dkpro-core-api-datasets-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/datasets/lib/gum-en-conll-2.3.2.yaml, dkpro-core-api-datasets-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/datasets/lib/gum-en-conll-3.0.0.yaml
=> #1272 - GUM dataset description license comment is wrong

dkpro-core-api-datasets-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/datasets/lib/gum-dep-stanford-en-4.1.0.yaml
- Added new dataset description
=> #1052 - Add GUM 4.1.0 dataset description

dkpro-core-castransformation-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/castransformation/internal/AlignmentStorage.java
- Commented out System.out logging used sometimes during development.
=> #1275 - ApplyChangesAnnotator uses print() messages

dkpro-core-io-tika-asl/pom.xml
=> #1284 - Upgrade to Apache Tika 1.19

dkpro-core-languagetool-asl/pom.xml
=> #1290 - Upgrade to LanguageTool 4.3

dkpro-core-io-brat-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/brat/BratWriter.java
- Actually check if the feature looks like an array before trying to access it as one
=> #1311 - Exception during detection of "slot features" in BratWriter

dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/ConllUReader.java, dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/ConllUWriter.java, dkpro-core-io-conll-asl/src/test/resources/conll/u/conllu-en-orig2.conll, dkpro-core-io-conll-asl/src/test/resources/conll/u/conllu-en-ref.conll
- Improved test for sentence IDs
=> #1160 - Better support for CoNLL-U v2 (1.11.0)

dkpro-core-io-bincas-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/bincas/BinaryCasWriter.java
=> #1323 - File extension generated by BinaryCasWriter does not contain dot

dkpro-core-opennlp-asl/pom.xml
- Bumped dependency version to 1.9.1
=> #1322 - Upgrade to OpenNLP 1.9.1

dkpro-core-io-brat-asl/pom.xml, dkpro-core-io-brat-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/brat/BratWriter.java, dkpro-core-io-brat-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/brat/DKPro2Brat.java
- Moved conversion code from BratWriter to DKPro2Brat
=> #1338 - Factor CAS <-> brat conversion code into Pojos

dkpro-core-icu-asl/pom.xml, pom.xml
=> #1357 - Upgrade to ICU4J 64.2

dkpro-core-api-resources-asl/pom.xml, dkpro-core-api-resources-asl/src/test/java/org/dkpro/core/api/resources/ResourceUtilsTest.java, dkpro-core-api-segmentation-asl/pom.xml, dkpro-core-api-segmentation-asl/src/test/java/org/dkpro/core/api/segmentation/CompoundTest.java, dkpro-core-decompounding-asl/pom.xml, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/dictionary/SimpleDictionaryTest.java, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/splitter/BananaSplitterTest.java, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/splitter/DataDrivenAlgorithmTest.java, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/splitter/DecompoundedWordTest.java, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/splitter/FragmentTest.java, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/splitter/JWordSplitterTest.java, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/splitter/LeftToRightSplitAlgorithmTest.java, dkpro-core-decompounding-asl/src/test/java/org/dkpro/core/decompounding/uima/annotator/CompoundAnnotatorTest.java, dkpro-core-lancaster-asl/pom.xml, pom.xml
- snakeyaml 1.19 -> 1.24
- commons-collections4 4.1 -> 4.3
- commons-coded 1.11 -> 1.12
- commons-lang 3.8 -> 3.9
- ant 1.10.2 -> 1.10.5
- fastutil 7.0.13 -> 8.2.2
- Drop hamcrest and use assertj instead
=> #1340 - Upgrade dependencies (1.11.0)

dkpro-core-corenlp-gpl/pom.xml, dkpro-core-corenlp-gpl/src/main/java/org/dkpro/core/corenlp/CoreNlpNamedEntityRecognizer.java, dkpro-core-corenlp-gpl/src/scripts/build.xml, dkpro-core-corenlp-gpl/src/test/java/org/dkpro/core/corenlp/CoreNlpCoreferenceResolverTest.java, dkpro-core-stanfordnlp-gpl/pom.xml, dkpro-core-stanfordnlp-gpl/src/scripts/build.xml
- Updated CoreNLP dependency
- Updated some English models
=> #1299 - Update to CoreNLP 3.9.2

dkpro-core-io-lif-asl/pom.xml, dkpro-core-io-lif-asl/src/test/resources/lif/stanford-pos-ref.lif
=> #1327 - Update LIF support

dkpro-core-io-tcf-asl/pom.xml, dkpro-core-io-tcf-asl/src/main/java/org/dkpro/core/io/tcf/TcfReader.java, dkpro-core-io-tcf-asl/src/main/java/org/dkpro/core/io/tcf/TcfWriter.java
- Backport orthography layer support from WebAnno
=> #1367 - Support TCF orthography via SofaChangeAnnotations

dkpro-core-api-parameter-asl/src/main/java/org/dkpro/core/api/parameter/MimeTypes.java, dkpro-core-asl/pom.xml, dkpro-core-io-conll-asl/pom.xml, dkpro-core-io-conll-asl/src/test/java/org/dkpro/core/io/conll/ConllUReaderTest.java, dkpro-core-io-perseus-asl/LICENSE.txt, dkpro-core-io-perseus-asl/pom.xml, dkpro-core-io-perseus-asl/src/main/java/org/dkpro/core/io/perseus/PerseusReader.java, dkpro-core-io-perseus-asl/src/main/java/org/dkpro/core/io/perseus/internal/model/PerseusSentence.java, dkpro-core-io-perseus-asl/src/main/java/org/dkpro/core/io/perseus/internal/model/PerseusWord.java, dkpro-core-io-tcf-asl/src/main/java/org/dkpro/core/io/tcf/TcfWriter.java
- Added a basic reader (adapted from the TigerXmlReader code)
=> #1368 - Support the Perseus Treebank XML format

dkpro-core-api-io-asl/pom.xml, dkpro-core-api-io-asl/src/main/java/org/dkpro/core/api/io/JCasFileWriter_ImplBase.java, dkpro-core-api-io-asl/src/test/java/org/dkpro/core/api/io/JCasFileWriter_ImplBaseTest.java
This is my proposed fix for this issue:
https://github.com/dkpro/dkpro-core/issues/1392
=> Unescape %20 in file names in JCasFileWriter_ImplBase

dkpro-core-api-xml-asl/src/main/java/org/dkpro/core/api/xml/Cas2SaxEvents.java, pom.xml
- Update version
- Adjust to minor API change
=> #1405 - Upgrade to UIMA 3.1.0

dkpro-core-languagetool-asl/src/main/java/org/dkpro/core/languagetool/LanguageToolChecker.java, dkpro-core-languagetool-asl/src/test/java/org/dkpro/core/languagetool/LanguageToolCheckerTest.java
- Fill in suggestions
- Add test using French
=> #1410 - LanguageToolChecker does not fill in suggestions

dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2000Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2002Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2003Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2006Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2008Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2009Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2012Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/ConllCoreNlpReader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/ConllUReader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/internal/ConllReader_ImplBase.java
- Trim CoNLL file field values (including token texts) by default
=> #1422 - Trim field values by default

dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/ConllUReader.java
- Set "p" as the div type on paragraphs
=> #1439 - CoNLL-U reader should set div type on paragraphs

dkpro-core-doc/src/main/asciidoc/format-reference/sectionIntroBrat.adoc
- Added documentation for the mappings configuration of the BratReader.
=> #1441 - Improve brat reader/writer documentation

dkpro-core-io-bincas-asl/src/main/java/org/dkpro/core/io/bincas/BinaryCasWriter.java, dkpro-core-io-bincas-asl/src/test/java/org/dkpro/core/io/bincas/BinaryCasWriterReaderTest.java
=> #1461 - BinaryCasWriter does not support BINARY_TSI

dkpro-core-opennlp-asl/pom.xml, dkpro-core-opennlp-asl/src/main/java/org/dkpro/core/opennlp/OpenNlpSnowballStemmer.java, dkpro-core-opennlp-asl/src/main/resources/org/dkpro/core/opennlp/OpenNlpSnowballStemmer_Messages.properties, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpSnowballStemmerTest.java
- Upgraded to OpenNLP 1.9.2
- Added the OpenNLP Snowball stemmer as a new component
=> #1463 - Upgrade to OpenNLP 1.9.2

dkpro-core-hunpos-asl/src/test/java/org/dkpro/core/hunpos/HunPosTaggerTest.java, dkpro-core-maltparser-asl/src/test/java/org/dkpro/core/maltparser/MaltParserTest.java, dkpro-core-matetools-gpl/src/test/java/org/dkpro/core/matetools/MateParserTest.java, dkpro-core-mstparser-asl/src/test/java/org/dkpro/core/mstparser/MstParserTest.java
- Skip hunpos-related tests on OS X Catalina
=> #1471 - Hunpos binaries do not run on OS X Catalina

dkpro-core-doc/pom.xml, dkpro-core-gosen-asl/pom.xml, dkpro-core-io-tei-asl/pom.xml, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpNamedEntityRecognizerTrainerTest.java, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpSentenceTrainerTest.java, dkpro-core-stanfordnlp-gpl/src/test/java/org/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizerTrainerTest.java, pom.xml
- Upgraded various dependencies
=> #1473 - Upgrade dependencies

dkpro-core-api-datasets-asl/src/main/resources/org/dkpro/core/api/datasets/lib/germeval2014-de.yaml, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpNamedEntityRecognizerTrainerTest.java, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpSentenceTrainerTest.java, dkpro-core-stanfordnlp-gpl/src/test/java/org/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizerTrainerTest.java, pom.xml
- Update GermEval dataset description
- Reactivate the tests
=> #1486 - Reactivate unit tests using GermEval 2014

dkpro-core-io-tei-asl/src/main/java/org/dkpro/core/io/tei/TeiWriter.java
- Added additional null checks
- Removed printf debugging code
=> #1498 - NPE in TeiWriter when NamedEntity value feature is null

dkpro-core-io-conll-asl/src/test/java/org/dkpro/core/io/conll/ConllUReaderWriterTest.java, dkpro-core-io-html-asl/pom.xml, dkpro-core-jtok-asl/pom.xml, pom.xml
- UIMA 3.1.1 -> 3.2.0
- uimaFIT 3.1.1 -> 3.2.0
- JSoup 1.13.1 -> 1.14.3
- Log4J 2.14.0 -> 2.16.0
- commons-io 2.8.0 -> 2.11.0
- commons-lang3 3.11 -> 3.12.0
- commons-compress 1.20 -> 1.21
- ant 1.10.9 -> 1.10.12
- Removed / commented out staging and SNAPSHOT repos
- Updated repo for JTok and removed bintray which no longer exists
- Minor cleaning up in ConllUReaderWriterTest
=> #1500 - Upgrade dependencies

dkpro-core-api-datasets-asl/pom.xml, dkpro-core-api-datasets-asl/src/main/java/org/dkpro/core/api/datasets/internal/actions/Explode.java, dkpro-core-api-parameter-asl/src/main/java/org/dkpro/core/api/parameter/Messages.java, dkpro-core-api-xml-asl/src/main/java/org/dkpro/core/api/xml/CasXmlHandler.java, dkpro-core-asl/pom.xml, dkpro-core-dictionaryannotator-asl/pom.xml, dkpro-core-illinoisnlp-asl/src/main/java/org/dkpro/core/illinoisnlp/IllinoisPosTagger.java, dkpro-core-io-brat-asl/src/main/java/org/dkpro/core/io/brat/BratReader.java, dkpro-core-io-brat-asl/src/main/java/org/dkpro/core/io/brat/BratWriter.java, dkpro-core-io-html-asl/pom.xml, dkpro-core-io-html-asl/src/main/java/org/dkpro/core/io/html/internal/JSoupUtil.java, dkpro-core-io-html-asl/src/test/java/org/dkpro/core/io/html/HtmlDocumentReaderTest.java, dkpro-core-io-html-asl/src/test/resources/html/test-document.xmi, dkpro-core-io-html-asl/src/test/resources/html/test-document.xml, dkpro-core-io-html-asl/src/test/resources/html/test-with-head-and-doctype.html, dkpro-core-io-html-asl/src/test/resources/html/test-with-head-and-doctype.xmi, dkpro-core-io-html-asl/src/test/resources/html/test-with-head.xmi, dkpro-core-io-pdf-asl/pom.xml, dkpro-core-io-rdf-asl/pom.xml, dkpro-core-io-tika-asl/pom.xml, dkpro-core-morpha-asl/src/main/java/org/dkpro/core/morpha/MorphaLemmatizer.java, dkpro-core-nlp4j-asl/src/main/java/org/dkpro/core/nlp4j/Nlp4JDependencyParser.java, dkpro-core-smile-asl/pom.xml, dkpro-core-snowball-asl/pom.xml, pom.xml
- DKPro Parent POM 25 -> 26
- SLF4J 1.7.30 -> 1.7.36
- Snakeyaml 1.27 -> 1.30
- Groovy 3.0.7 -> 3.0.10
- Jackson 2.12.1 -> 2.13.2
- junrar 4.0.0 -> 7.4.1
- Spring 4.3.30 -> 5.3.22
- log4j 2.16.0 -> 2.17.2
- junit 4.13.1 -> 4.13.2
- assertj-core 3.18.1 -> 3.22.0
- xerces 2.12.0 -> 2.12.2
- jsoup 1.14.3 -> 1.15.3
=> #1500 - Upgrade dependencies (2.2.1)

dkpro-core-api-xml-asl/pom.xml, dkpro-core-api-xml-asl/src/main/java/org/dkpro/core/api/xml/XmlParserUtils.java, dkpro-core-io-ancora-asl/pom.xml, dkpro-core-io-ancora-asl/src/main/java/org/dkpro/core/io/ancora/AncoraReader.java, dkpro-core-io-gigaword-asl/pom.xml, dkpro-core-io-gigaword-asl/src/main/java/org/dkpro/core/io/gigaword/internal/AnnotatedGigawordDocuments.java, dkpro-core-io-xml-asl/pom.xml, dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/InlineXmlWriter.java, dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/XmlDocumentReader.java, dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/XmlDocumentWriter.java, dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/XmlTextReader.java, dkpro-core-testing-asl/src/main/java/org/dkpro/core/testing/validation/checks/AllAnnotationsIndexedCheck.java, pom.xml
- Create XML factories via XmlParserUtils
=> #1537 - Centralize creation of XML factories

dkpro-core-io-nif-asl/src/main/java/org/dkpro/core/io/nif/internal/DKPro2Nif.java, pom.xml
- Java 8 -> 11
- Jena 3.17.0 -> 4.6.1
=> #1539 - Upgrade dependencies (2.3.x)

dkpro-core-api-embeddings-asl/src/main/java/org/dkpro/core/api/embeddings/binary/BinaryWordVectorUtils.java, dkpro-core-io-lxf-asl/src/main/java/org/dkpro/core/io/lxf/internal/NodeIterator.java
- Remove author tags per project policy - author information is retained either in repository history or in copyright header / NOTICE file - as appropriate
=> #1504 - Author tags

dkpro-core-api-resources-asl/pom.xml, dkpro-core-api-resources-asl/src/main/java/org/dkpro/core/api/resources/ResourceObjectProviderBase.java, dkpro-core-api-resources-asl/src/main/java/org/dkpro/core/api/resources/ResourceObjectResolver.java, dkpro-core-asl/pom.xml, dkpro-core-ivy-resolver-asl/LICENSE.txt, dkpro-core-ivy-resolver-asl/pom.xml, dkpro-core-ivy-resolver-asl/src/main/java/org/dkpro/core/resolver/ivy/IvyResourceObjectResolver.java, dkpro-core-ivy-resolver-asl/src/main/resources/META-INF/services/org.dkpro.core.api.resources.ResourceObjectResolver, dkpro-core-opennlp-asl/pom.xml
- Factor out Ivy resource resolving into a separate module and link it up using an SPI
=> #1508 - Move model-downloading code out of resources-api

dkpro-core-tokit-asl/pom.xml, dkpro-core-tokit-asl/src/main/java/org/dkpro/core/tokit/TokenMerger.java, dkpro-core-tokit-asl/src/test/java/org/dkpro/core/tokit/TokenMergerTest.java
- Removed the parameter
- Changed some tests such that they work without JXPath
=> #1555 - Remove constraints parameter on token merger

dkpro-core-api-lexmorph-asl/src/main/resources/org/dkpro/core/api/lexmorph/tagset/da-ddt-pos.map
=> #1520 - Danish UD17 Tag Mapping Typo

dkpro-core-api-datasets-asl/pom.xml, dkpro-core-asl/pom.xml, dkpro-core-build/src/main/resources/dkpro-core/version-rules.xml, dkpro-core-flextag-asl/pom.xml, dkpro-core-gate-asl/pom.xml, dkpro-core-gpl/pom.xml, dkpro-core-illinoisnlp-asl/pom.xml, dkpro-core-io-gate-asl/pom.xml, dkpro-core-io-gate-asl/src/test/java/org/dkpro/core/io/gate/GateXmlWriterTest.java, dkpro-core-io-gate-asl/src/test/java/org/dkpro/core/io/gate/GateXmlWriterTest2.java, dkpro-core-io-gate-asl/src/test/resources/conll/2000/chunk2000_ref2.xml, dkpro-core-io-html-asl/pom.xml, dkpro-core-io-html-asl/src/test/java/org/dkpro/core/io/html/HtmlDocumentReaderTest.java, dkpro-core-io-html-asl/src/test/java/org/dkpro/core/io/html/HtmlReaderTest.java, dkpro-core-io-jwpl-asl/pom.xml, dkpro-core-io-lcc-asl/pom.xml, dkpro-core-io-tika-asl/pom.xml, dkpro-core-kuromoji-asl/pom.xml, dkpro-core-kuromoji-asl/src/test/java/org/dkpro/core/kuromoji/KuromojiSegmenterTest.java, dkpro-core-languagetool-asl/pom.xml, dkpro-core-languagetool-asl/src/test/java/org/dkpro/core/languagetool/LanguageToolSegmenterTest.java, dkpro-core-lbj-asl/pom.xml, dkpro-core-smile-asl/pom.xml, pom.xml
- Illinois CogComp NLP 4.0.7 -> 4.0.13
- LanguageTool 5.2 -> 6.1
- GATE 8.2 -> 8.6.1
- commons-cli 1.4 -> 1.5.0
- commons-io 2.11.0 -> 2.13.0
- commons-compress 1.21 -> 1.23.0
- checkstyle 8.31 -> 8.45.1
- junrar 7.4.1 -> 7.5.4
- jsoup 1.15.3 -> 1.16.1
- tika 2.6.0 -> 2.8.0
- icu4j 68.2 -> 73.1
- guava 30.1-jre -> 32.0.1-jre
- Smile 2.6.0 -> 3.0.1
=> #1560 - Upgrade dependencies

dkpro-core-api-datasets-asl/pom.xml, dkpro-core-api-datasets-asl/src/test/resources/log4j2-test.xml, dkpro-core-asl/pom.xml, dkpro-core-build/src/main/resources/dkpro-core/version-rules.xml, dkpro-core-corenlp-gpl/pom.xml, dkpro-core-fs-hdfs-asl/pom.xml, dkpro-core-io-bincas-asl/src/main/java/org/dkpro/core/io/bincas/BinaryCasReader.java, dkpro-core-io-bincas-asl/src/main/java/org/dkpro/core/io/bincas/SerializedCasReader.java, dkpro-core-io-html-asl/pom.xml, dkpro-core-io-jdbc-asl/pom.xml, dkpro-core-io-tika-asl/pom.xml, dkpro-core-ixa-asl/pom.xml, dkpro-core-languagetool-asl/pom.xml, dkpro-core-opennlp-asl/pom.xml, dkpro-core-opennlp-asl/src/main/java/org/dkpro/core/opennlp/OpenNlpTokenTrainer.java, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpPosTaggerTrainerTest.java, dkpro-core-opennlp-asl/src/test/resources/log4j2-test.xml, dkpro-core-smile-asl/pom.xml, dkpro-core-testing-asl/pom.xml, dkpro-core-testing-asl/src/main/java/org/dkpro/core/testing/validation/CasValidator.java, dkpro-core-testing-asl/src/main/java/org/dkpro/core/testing/validation/checks/Check.java, pom.xml
- junrar 7.5.4 -> 7.5.5
- corenlp 4.5.1 -> 4.5.5
- hadoop 3.3.3 -> 3.3.6
- jsoup 1.16.1 -> 1.16.2
- commons-dbutils 1.7 -> 1.8.1
- hsqldb 2.7.1 -> 2.7.2
- tika 2.8.0 -> 2.9.1
- opennlp 2.0.0 -> 2.3.0 (except in IXA module)
- languagetool 6.1 -> 6.3
- smile 3.0.1 -> 3.0.2
- reflections 0.9.10 -> 0.10.2
- junit 5.9.3 -> 5.10.0
- junit-platform 1.9.3 -> 1.10.0
- groovy 4.0.11 -> 4.0.15
- icu4j 73.1 -> 74.1
- jackson 2.15.1 -> 2.15.3
- log4j 2.20.0 -> 2.21.1
- slf4j 2.0.7 -> 2.0.9
- snakeyaml 2.0 -> 2.2
- woodstox-core 6.5.0 -> 6.5.1
- commons-cli 1.5.0 -> 1.6.0
- commons-codec 1.15 -> 1.16.0
- commons-io 2.13.0 -> 2.15.0
- commons-text 1.10.0 -> 1.11.0
- commons-lang 3.12.0 -> 3.13.0
- commons-compress 1.23.0 -> 1.24.0
- xom 1.3.8 -> 1.3.9
- dom4j 2.1.3 -> 2.1.4
- guava …
=> #1571 - Upgrade dependencies

dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/internal/tsv3x/Tsv3XDeserializer.java, dkpro-core-io-webanno-asl/src/test/java/org/dkpro/core/io/webanno/tsv/WebAnnoTsv3XReaderTest.java
=> #1575 - Relation offsets not set in WebAnnoTsv3XReader

dkpro-core-io-text-asl/src/main/java/org/dkpro/core/io/text/TextReader.java, dkpro-core-io-text-asl/src/test/java/org/dkpro/core/io/text/TextReaderTest.java
- Remove BOM by default
- Parameter to allow keeping it
- Added test
=> #1584 - Strip out BOM when reading text files

dkpro-core-languagetool-asl/src/test/java/org/dkpro/core/languagetool/LanguageToolSegmenterTest.java, dkpro-core-testing-asl/src/main/java/org/dkpro/core/testing/AssertAnnotations.java
- Improved assert
- Added unit test
=> #811 - LanguageToolSegmenter chokes on "丁肇中"

dkpro-core-opennlp-asl/pom.xml, dkpro-core-opennlp-asl/src/main/resources/org/dkpro/core/opennlp/lib/lemma-default-variants.map, dkpro-core-opennlp-asl/src/scripts/build.xml
- Added OpenNLP German GSD lemmatizer model
=> #1599 - Add German lemmatizer model for OpenNLP
