de.tudarmstadt.ukp.dkpro.core.stanfordnlp-gpl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/lib/ner-es-ancora.distsim.s512.crf.map
The missing fallback causes this exception when using Spanish NER on 1.8.0-SNAPSHOT: 
java.lang.IllegalStateException: No fallback (*) mapping defined!
at de.tudarmstadt.ukp.dkpro.core.api.resources.MappingProvider.getTagTypeName(MappingProvider.java:106)
at de.tudarmstadt.ukp.dkpro.core.api.resources.MappingProvider.getTagType(MappingProvider.java:72)
=> Add missing fallback (*) to ner-es mapping

dkpro-core-api-lexmorph-asl/src/main/resources/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/de-tiger-rftagger-morph.map
Hi,
This pull request fixes several issues in the morph mapping file for the `RfTagger`. See [1] for more information. It also adds the original mapping reference for documentation purpose and enables `Mood` for `VFIN`. I've also updated a wrong `Degree` label. 
Best Uli
[1] https://groups.google.com/forum/#!topic/dkpro-core-user/wRk20eI6sPc
=> Fix RfTagger morph mapping

dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2002Reader.java
Updated the javadoc for PARAM_COLUMN_SEPARATOR and added a usage example to make it more clear.
=> Updated javadoc for PARAM_COLUMN_SEPARATOR

dkpro-core-snowball-asl/pom.xml
Fixes a POM dependency error, which caused maven build problems. Please just reject if this patch is not appropriate or already done elsewhere.
=> fix(pom): Snowball POM of 1.8 branch was referencing 1.9.0

dkpro-core-castransformation-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/castransformation/Backmapper.java
The Backmapper breaks if feature structures are not subtypes of Annotation like the CoreferenceChain type produced by the DKPro Stanford coreference analyser.
Caused by: java.lang.ClassCastException: de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceChain cannot be cast to org.apache.uima.jcas.tcas.Annotation
at de.tudarmstadt.ukp.dkpro.core.castransformation.Backmapper.updateOffsets(Backmapper.java:166)
at de.tudarmstadt.ukp.dkpro.core.castransformation.Backmapper.process(Backmapper.java:120)
at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
... 16 more
This fix just ignores those feature …
=> Backmapper breaks if feature structures are not subtypes of Annotation

dkpro-core-io-bincas-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/bincas/BinaryCasReader.java, dkpro-core-io-bincas-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/io/bincas/BinaryCasWriterReaderTest.java, pom.xml
Added a parameter PARAM_MERGE_TYPESYSTEM in BinaryCasReader to make it possible to turn the merging of the typeSystems on and off. 
The original typesystem is loaded in typeSystemInit().  
Modified the tests to run read() with both cases.
=> Added possibility to merge typesystems in BinaryCasReader

dkpro-core-opennlp-asl/pom.xml, dkpro-core-opennlp-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpLemmatizer.java, dkpro-core-opennlp-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/opennlp/internal/CasLemmaSampleStream.java, dkpro-core-opennlp-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/opennlp/internal/OpenNlpParserTagsetDescriptionProvider.java, dkpro-core-opennlp-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpNamedEntityRecognizerTrainerTest.java, dkpro-core-opennlp-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/opennlp/OpenNlpPosTaggerTrainerTest.java
Issue #1065 
**Tests in failure**
```
Results :
Failed tests: 
OpenNlpNamedEntityRecognizerTrainerTest.test:114 expected:<0.321976> but was:<0.3232536643338175>
OpenNlpPosTaggerTrainerTest.test:109 expected:<0.646981> but was:<0.6422120750887874>
Tests in error: 
OpenNlpParserTest.testEnglish » OutOfMemory Java heap space
Tests run: 28, Failures: 2, Errors: 1, Skipped: 13
```
=> #1065: Update OpenNLP 1.8.0 ref and usage of Lemmatizer and Chunker

dkpro-core-io-xmi-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/xmi/XmiWriter.java
Like other writers, the user should be able to configure the filename extension.
=> Add filenameSuffix to XmiWriter

dkpro-core-tokit-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/tokit/RegexSegmenter.java, dkpro-core-tokit-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/tokit/RegexSegmenterTest.java
The `RegexSegmenter` did not use the `zoneBegin` parameter. In cases where a `Div` has been added to the `JCas` (see example below), the segmentation did not work. This PR fixes this issue. 
```java
JCas jcas = JCasFactory.createText("This is sentence 1 .\nThis is number 2 .", "en");
Div d = new Div(jcas, 0, 20);
d.addToIndexes();
d = new Div(jcas, 21, 39);
d.addToIndexes();
```
=> Fix RegexSegmenter: use zoneBegin parameter

dkpro-core-api-io-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/api/io/JCasFileWriter_ImplBase.java
Handle case that location is URL-encoded and fall back to assuming it is not URL-encoded if decoding fails.
=> #1093 - Writing to JARs fails if target location is URL-encoded

dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizerTrainer.java, dkpro-core-stanfordnlp-gpl/src/main/java/de/tudarmstadt/ukp/dkpro/core/stanfordnlp/StanfordPosTaggerTrainer.java
- Fix Stanford tagger trainer: provide default values if cluster file is not provided and use simple name to generate POS value
- Fix Stanford ner trainer: check if properties files has been provided
- Fix OpenNLP tagger trainer: use simple name to generate POS value
=> Provide default values if cluster file is not provided in StanfordPosTaggerTrainer

dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2012Reader.java
Fix for #1188.
I didn't commit the test because I can't run it, because other tests fail (see below).
```
=== testConvertWordVectorsToBinaryCaseSensitive =====================
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/log4j/Level
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
```
=> prevents NullPointerException when syntax columns are empty, fix 1188

pages/maven.md
The tags used in the XML were wrong, and the group and artifact were
the wrong way around.
=> Fix the documentation for the dependency POM.

dkpro-core-asl/pom.xml, dkpro-core-cogroo-asl/pom.xml, dkpro-core-gpl/pom.xml, dkpro-core-io-annis-asl/pom.xml, dkpro-core-io-cermine-gpl/pom.xml, dkpro-core-io-fangorn-asl/pom.xml, dkpro-core-io-gate-asl/pom.xml, dkpro-core-io-graf-asl/pom.xml, dkpro-core-io-rdf-asl/pom.xml, dkpro-core-kuromoji-asl/pom.xml, dkpro-core-lbj-asl/pom.xml, dkpro-core-udpipe-asl/pom.xml, pom.xml
=> #1207 - Update OMTD-SHARE plugin to support "non-standard" licenses

dkpro-core-doc/src/main/asciidoc/format-reference/sectionIntroConll2006.adoc
Links to some corpora are outdated in the CoNLL 2006 format description.
=> Links to some corpora are outdated

dkpro-core-lbj-asl/pom.xml, dkpro-core-lbj-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/lbj/IllinoisStatefulSegmenter.java, dkpro-core-lbj-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/lbj/IllinoisPosTaggerTest.java, dkpro-core-lbj-asl/src/test/java/de/tudarmstadt/ukp/dkpro/core/lbj/IllinoisStatefulSegmenterTest.java, dkpro-core-lbj-asl/src/test/resources/log4j.properties
- Upgrade to CogComp 4.0.7
- Adust stateful segmenter unit test
- Exclude GPL dependencies
- Add note to POM about academic-only use
- Removed explicit LBJava dependency
- Increase memory for unit tests
=> #825 - Upgrade Illinois components

dkpro-core-io-tika-asl/src/main/java/org/dkpro/core/io/tika/TikaReader.java
- Added parameter to configure the internal buffer size.
- Use an unlimited buffer by default.
=> #1286 - Tika 100000 characters Limit

dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java
- Improve error messages in TSV3 when an annotation cannot be persisted because it starts before the first token or ends beyond the last token.
=> #1358 - Improve error messages in TSV3

dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2012Reader.java, dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/Conll2012Writer.java
- Added capabilities for CoreferenceHain, NamedEntity, and WordSense to CoNLL 2012 reader and writer
=> #1337 - Connl2012 writer uses WordSense, but does not declare it

dkpro-core-api-xml-asl/.activate-run-jcasgen, dkpro-core-api-xml-asl/LICENSE.txt, dkpro-core-api-xml-asl/pom.xml, dkpro-core-api-xml-asl/src/main/java/org/dkpro/core/api/xml/Cas2SaxEvents.java, dkpro-core-api-xml-asl/src/main/java/org/dkpro/core/api/xml/CasXmlHandler.java, dkpro-core-api-xml-asl/src/main/resources/META-INF/org.apache.uima.fit/types.txt, dkpro-core-api-xml-asl/src/main/resources/desc/type/XmlStructure.xml, dkpro-core-api-xml-asl/suppressions.xml, dkpro-core-asl/pom.xml, dkpro-core-io-html-asl/pom.xml, dkpro-core-io-html-asl/src/main/java/org/dkpro/core/io/html/HtmlDocumentReader.java, dkpro-core-io-html-asl/src/main/java/org/dkpro/core/io/html/internal/JSoupUtil.java, dkpro-core-io-html-asl/src/main/java/org/dkpro/core/io/html/internal/TrimUtils.java, dkpro-core-io-html-asl/src/test/java/org/dkpro/core/io/html/HtmlDocumentReaderTest.java, dkpro-core-io-html-asl/src/test/resources/html/test-document.xmi, dkpro-core-io-html-asl/src/test/resources/html/test-document.xml, dkpro-core-io-html-asl/src/test/resources/html/test-with-head.html, dkpro-core-io-html-asl/src/test/resources/html/test-with-head.xmi, dkpro-core-io-xml-asl/pom.xml, dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/XmlDocumentReader.java, dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/XmlDocumentWriter.java, dkpro-core-io-xml-asl/src/test/java/org/dkpro/core/io/xml/SimpleXmlReaderWriterTest.java, dkpro-core-io-xml-asl/src/test/resources/xml/basic.xml
- UIMA types to capture XML structure in the CAS
- Reader/writer for document-oriented XML
- New HtmlDocumentReader capturing the HTML structure in the CAS
- Unit tests
=> #1379 - Add generic XML types

dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java, dkpro-core-io-webanno-asl/src/test/java/org/dkpro/core/io/webanno/tsv/WebAnnoTsv3WriterTestBase.java, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithLeadingWhitespace/reference.tsv, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithLeadingWhitespace/reference.xmi, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithLeadingWhitespaceAtStart/reference.tsv, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithLeadingWhitespaceAtStart/reference.xmi, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithTrailingWhitespace/reference.tsv, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithTrailingWhitespace/reference.xmi, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithTrailingWhitespaceAtEnd/reference.tsv, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testAnnotationWithTrailingWhitespaceAtEnd/reference.xmi
=> #1381 - Annotations starting/ending in inter-token space cause exception

.gitignore, dkpro-core-asl/pom.xml, dkpro-core-io-html-asl/pom.xml, dkpro-core-io-html-asl/src/main/java/org/dkpro/core/io/html/HtmlDocumentReader.java, dkpro-core-io-html-asl/src/test/java/org/dkpro/core/io/html/HtmlDocumentReaderTest.java, dkpro-core-io-html-asl/src/test/resources/html/test-document.xml, dkpro-core-io-xml-asl/src/main/java/org/dkpro/core/io/xml/XmlDocumentWriter.java
- Added option to enable/disable whitespace normalization in HtmlDocumentReader
- Disable whitespace normalization in the HtmlDocumentReader which writes the document out as XML
- Adjusted reference data for this test
- Added parameters to XmlDocumentWriter to control indentation (off by default) and output method (XML by default)
=>  #1404 - JDK 12 processes XML differently

dkpro-core-io-conll-asl/src/main/java/org/dkpro/core/io/conll/ConllUWriter.java, dkpro-core-io-conll-asl/src/test/java/org/dkpro/core/io/conll/ConllUWriterTest.java, dkpro-core-io-conll-asl/src/test/resources/conll/u_v2/conllu-linebreaks.conll
- Replace line breaks and carriage returns with spaces during export
- Added unit test
=> #1413 - CoNLL-U export broken if text contains line breaks

dkpro-core-io-cermine-gpl/pom.xml, dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java, dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/internal/tsv3x/Tsv3XSerializer.java, dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/internal/tsv3x/model/TsvSchema.java, dkpro-core-io-webanno-asl/src/main/java/org/dkpro/core/io/webanno/tsv/internal/tsv3x/model/TsvUnit.java, dkpro-core-io-webanno-asl/src/test/java/org/dkpro/core/io/webanno/tsv/WebAnnoTsv3WriterTestBase.java, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testElevatedType/reference.tsv, dkpro-core-io-webanno-asl/src/test/resources/tsv3-suite/testElevatedType/reference.xmi
- Export elevated types as whichever of their supertypes is actually part of the TsvSchema (i.e. a subtype of Annotation)
- Added unit test
=> #1434 - WebAnnoTsv3XWriter does not support elevated types

dkpro-core-opennlp-asl/src/scripts/build.xml, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpPosTaggerBulkTest.java, dkpro-core-opennlp-asl/src/test/java/org/dkpro/core/opennlp/OpenNlpPosTaggerTest.java
- Removed the IXA models that are no longer there from the build.xml script (keep them in the POM though)
- Update to a newer version of the Ant packaging script
- Slight refactoring of the POS tests
=> #1465 - Drop missing IXA models for OpenNLP

pom.xml
- jackson 2.14.0 -> 2.14.1
- spring 5.3.23 -> 5.3.24
- assertj 3.22.0 -> 3.23.1
- mockito 4.8.1 -> 4.11.0
- xz 1.8 -> 1.9
- fastutil 8.4.4 -> 8.5.11
=> #1539 - Upgrade dependencies

dkpro-core-build/src/main/resources/dkpro-core/checkstyle.xml, dkpro-core-io-xmi-asl/pom.xml, dkpro-core-io-xmi-asl/src/main/java/org/dkpro/core/io/xmi/XmiWriter.java, dkpro-core-io-xmi-asl/src/main/java/org/dkpro/core/io/xmi/internal/IllegalXmlCharacterSanitizingContentHandler.java, dkpro-core-io-xmi-asl/src/test/java/org/dkpro/core/io/xmi/XmiReaderWriterTest.java, dkpro-core-io-xmi-asl/src/test/java/org/dkpro/core/io/xmi/XmiWriterReaderTest.java, dkpro-core-io-xmi-asl/src/test/java/org/dkpro/core/io/xmi/internal/IllegalXmlCharacterSanitizingContentHandlerTest.java
- Added option to replace illegal characters
* Enable the option using the new parameter and write a file that contains illegal characters.
=> #1565 - Option to replace illegal characters in XMI files

dkpro-core-io-tei-asl/src/main/java/org/dkpro/core/io/tei/TeiReader.java, dkpro-core-io-tei-asl/src/main/java/org/dkpro/core/io/tei/TeiWriter.java, dkpro-core-io-tei-asl/src/main/java/org/dkpro/core/io/tei/internal/TeiConstants.java, dkpro-core-io-tei-asl/src/test/java/org/dkpro/core/io/tei/TeiReaderTest.java, dkpro-core-io-tei-asl/src/test/java/org/dkpro/core/io/tei/TeiWriterTest.java, dkpro-core-io-tei-asl/src/test/resources/with_xml_id/input-ref.xml, dkpro-core-io-tei-asl/src/test/resources/with_xml_id/input.xml
- Preserve xml:ids on sentence, paragraph and token
=> #1570 - Support xml id on certain TEI elements
